//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CJRGaming.MMO.Server.SubServer {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class SubServerSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static SubServerSettings defaultInstance = ((SubServerSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SubServerSettings())));
        
        public static SubServerSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string MasterIPAddress {
            get {
                return ((string)(this["MasterIPAddress"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string PublicIPAddress {
            get {
                return ((string)(this["PublicIPAddress"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4531")]
        public int GamingTcpPort {
            get {
                return ((int)(this["GamingTcpPort"]));
            }
            set {
                this["GamingTcpPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5056")]
        public int GamingUdpPort {
            get {
                return ((int)(this["GamingUdpPort"]));
            }
            set {
                this["GamingUdpPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public int ConnectReytryInterval {
            get {
                return ((int)(this["ConnectReytryInterval"]));
            }
            set {
                this["ConnectReytryInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4520")]
        public int OutgoingMasterServerPeerPort {
            get {
                return ((int)(this["OutgoingMasterServerPeerPort"]));
            }
            set {
                this["OutgoingMasterServerPeerPort"] = value;
            }
        }
    }
}
